#!/bin/bash

FILE="/home/${USER}/.local/share/qutebrowser/history.sqlite"
TIME="$(date +%s --date="3 months ago")";
if [[ ! -z "$1" ]]; then
	TIME="$(date +%s --date="$1")";
fi 

CMD="delete from CompletionHistory where last_atime < "
# CMD="select * from CompletionHistory where last_atime < "

CMD="$CMD $TIME"
sqlite3 ${FILE} "${CMD}"

CMD="delete from History where atime < "
# CMD="select * from History where atime < "

CMD="$CMD $TIME"
sqlite3 ${FILE} "${CMD}"

exit $?
