#!/usr/bin/env bash


if [[ ! -p $HOME/.mpvinput ]]; then
    mkfifo $HOME/.mpvinput
fi

URL=''
if [[ ! -z "$QUTE_SELECTED_TEXT" ]]; then
	URL="$QUTE_SELECTED_TEXT"
elif [[ ! -z "$1" ]]; then
	URL="$1"
else
	URL="$QUTE_URL"
fi
TITLE=`wget -qO- "$URL" |   perl -l -0777 -ne 'print $1 if /<title.*?>\s*(.*?)\s*<\/title/si'`
echo "[INFO]: `date` - appending: $URL - $TITLE" >> "$HOME/mpv_list.log"
if pgrep mpv > /dev/null
then
    printf "%s\n" "loadfile \"$URL\" append-play" > $HOME/.mpvinput
else
    mpv --no-terminal --x11-name=MPV-Q --input-file=$HOME/.mpvinput --player-operation-mode=pseudo-gui "$URL" &
fi
exit 0
